"""Curated business hierarchy for the Vetrellis Animal Health demo model.

Level B1 = BusinessDomain, B2 = Capability, B3 = Process, B4 = Activity.
Shape: DOMAINS[i] = dict(name, description, owner, importance, maturity, health,
                         capabilities=[dict(name, description, owner, importance,
                                            maturity, health, processes=[(name, desc)])])
"""

DOMAINS = [
    dict(
        name="Discover & Develop Products",
        description="Find and prove new animal-health compounds, biologics and delivery devices before they can ever be sold.",
        owner="VP Research & Development",
        importance="strategic", maturity=3, health="watch",
        capabilities=[
            dict(name="Research Portfolio Management",
                 description="Decide which research bets the company funds, and stop the ones that are not paying off.",
                 owner="Head of R&D Portfolio", importance="strategic", maturity=3, health="ok",
                 processes=[
                     ("Portfolio Prioritization", "Score and rank candidate research programmes against strategic and commercial criteria."),
                     ("Research Project Intake", "Capture, qualify and approve new research proposals from the science teams."),
                     ("Discovery Budget Tracking", "Track committed and actual spend per research programme against its approved envelope."),
                 ]),
            dict(name="Compound & Biologic Discovery",
                 description="Turn biological targets into viable drug candidates for companion and production animals.",
                 owner="Director, Discovery Science", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Target Identification", "Identify and validate biological targets worth pursuing for a given indication."),
                     ("Compound Screening", "Run high-throughput screens against target libraries and capture assay results."),
                     ("Lead Optimization", "Iteratively refine promising leads for potency, selectivity and safety."),
                 ]),
            dict(name="Preclinical Development",
                 description="Prove a candidate is safe and effective enough to justify clinical study in the target species.",
                 owner="Director, Preclinical", importance="core", maturity=3, health="watch",
                 processes=[
                     ("In Vitro Study Execution", "Design, run and record laboratory studies performed outside a living animal."),
                     ("Animal Model Study Execution", "Run welfare-compliant animal model studies and capture observations and endpoints."),
                     ("Toxicology Assessment", "Establish safety margins and adverse effect profiles for a candidate."),
                 ]),
            dict(name="Formulation & Device Development",
                 description="Turn an active molecule into a stable, administrable product a veterinarian or farmer can actually use.",
                 owner="Head of Pharmaceutical Development", importance="core", maturity=2, health="at-risk",
                 processes=[
                     ("Formulation Design", "Develop and trial candidate formulations, excipients and dose forms."),
                     ("Stability Study Management", "Plan, pull and evaluate stability timepoints that set product shelf life."),
                     ("Delivery Device Engineering", "Design and test applicators, injectors and other delivery hardware."),
                 ]),
        ]),
    dict(
        name="Manage Clinical & Regulatory Affairs",
        description="Prove products in the field and get and keep the licences that allow them to be marketed in each country.",
        owner="VP Regulatory Affairs",
        importance="core", maturity=4, health="ok",
        capabilities=[
            dict(name="Clinical Trial Management",
                 description="Run field and target-animal studies that generate the evidence regulators demand.",
                 owner="Head of Clinical Operations", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Study Design & Protocol Authoring", "Write, review and approve the protocol that governs a clinical study."),
                     ("Site Selection & Activation", "Qualify, contract and activate the veterinary practices and farms that run a study."),
                     ("Clinical Data Capture", "Collect investigator observations and study endpoints into a validated system."),
                 ]),
            dict(name="Regulatory Submission Management",
                 description="Assemble and file dossiers with health authorities and track them through to approval.",
                 owner="Director, Regulatory Operations", importance="core", maturity=4, health="ok",
                 processes=[
                     ("Dossier Assembly", "Compile study reports, quality data and labelling into a submission-ready dossier."),
                     ("Health Authority Submission", "Transmit dossiers to agencies through the required electronic gateways."),
                     ("Submission Tracking", "Track submission status, agency questions and commitment due dates."),
                 ]),
            dict(name="Regulatory Intelligence & Labeling",
                 description="Know what the rules are in every market and keep product labelling legally correct.",
                 owner="Head of Regulatory Intelligence", importance="supporting", maturity=3, health="watch",
                 processes=[
                     ("Regulatory Change Monitoring", "Watch agency publications for rule changes that affect marketed products."),
                     ("Label Content Management", "Author and version the approved text that appears on product labelling."),
                     ("Artwork Approval", "Route printed packaging artwork through regulatory and quality approval."),
                 ]),
            dict(name="Pharmacovigilance",
                 description="Detect and report harm caused by marketed products so licences and animals stay protected.",
                 owner="Qualified Person for Pharmacovigilance", importance="core", maturity=4, health="ok",
                 processes=[
                     ("Adverse Event Intake", "Receive suspected adverse event reports from vets, farmers and distributors."),
                     ("Case Processing & Assessment", "Code, assess causality and medically review each safety case."),
                     ("Periodic Safety Reporting", "Produce and file the periodic safety update reports agencies require."),
                 ]),
        ]),
    dict(
        name="Manufacture & Ensure Quality",
        description="Make product at scale, to specification, under GxP rules, and release only what is proven fit for use.",
        owner="VP Manufacturing & Quality",
        importance="core", maturity=4, health="watch",
        capabilities=[
            dict(name="Production Planning & Execution",
                 description="Convert the plan into physical batches on the line without breaking schedule or compliance.",
                 owner="Plant Manager, Rathdrum", importance="core", maturity=3, health="watch",
                 processes=[
                     ("Master Production Scheduling", "Turn demand and capacity into a firm, sequenced production schedule."),
                     ("Batch Execution & Recording", "Execute the batch recipe and capture the electronic batch record as it happens."),
                     ("Line Changeover Management", "Clear, clean and re-configure a line between products safely and quickly."),
                 ]),
            dict(name="Quality Control Testing",
                 description="Test material and product so quality claims rest on data, not assumption.",
                 owner="QC Laboratory Manager", importance="core", maturity=4, health="ok",
                 processes=[
                     ("Sample Management", "Register, label, route and store samples through their testing lifecycle."),
                     ("Analytical Testing", "Execute validated analytical methods and record the resulting data."),
                     ("Out-of-Specification Investigation", "Investigate failing results and determine whether they are valid."),
                 ]),
            dict(name="Quality Assurance & Compliance",
                 description="Keep the quality system healthy so product can be released and inspections survived.",
                 owner="Head of Quality Assurance", importance="core", maturity=4, health="ok",
                 processes=[
                     ("Deviation Management", "Record, investigate and close departures from approved procedure."),
                     ("CAPA Management", "Drive corrective and preventive actions to effective closure."),
                     ("Batch Release & Disposition", "Review the batch record and formally release or reject each batch."),
                 ]),
            dict(name="Equipment & Facility Management",
                 description="Keep plant, instruments and facilities qualified, calibrated and available.",
                 owner="Engineering Manager", importance="supporting", maturity=3, health="watch",
                 processes=[
                     ("Preventive Maintenance", "Plan and perform scheduled maintenance before equipment fails."),
                     ("Calibration Management", "Keep measuring instruments within calibration and evidence it."),
                     ("Cleaning Validation", "Prove cleaning procedures remove residues to acceptable limits."),
                 ]),
            dict(name="Technology Transfer & Scale-Up",
                 description="Move a product from development scale to commercial scale, or between sites, without losing quality.",
                 owner="Director, Technical Operations", importance="supporting", maturity=2, health="at-risk",
                 processes=[
                     ("Process Characterization", "Establish the design space and critical parameters of a process."),
                     ("Site Transfer Execution", "Transfer a validated process to a receiving manufacturing site."),
                     ("Validation Documentation", "Author and maintain the validation package supporting a process or system."),
                 ]),
        ]),
    dict(
        name="Manage Supply Chain & Logistics",
        description="Get the right materials in and the right product out, in the right condition, at the right time.",
        owner="VP Supply Chain",
        importance="core", maturity=3, health="watch",
        capabilities=[
            dict(name="Demand & Supply Planning",
                 description="Forecast what the market will need and shape supply to meet it without excess stock.",
                 owner="Head of Planning", importance="core", maturity=3, health="watch",
                 processes=[
                     ("Demand Forecasting", "Produce statistical and consensus forecasts of future product demand."),
                     ("Supply Network Planning", "Balance production, inventory and distribution across the network."),
                     ("Inventory Optimization", "Set and maintain stock targets that protect service at acceptable cost."),
                 ]),
            dict(name="Procurement & Supplier Management",
                 description="Buy materials and services from suppliers that are qualified, compliant and performing.",
                 owner="Head of Procurement", importance="supporting", maturity=3, health="ok",
                 processes=[
                     ("Supplier Qualification", "Assess, audit and approve suppliers of GxP and non-GxP materials."),
                     ("Purchase Order Management", "Raise, approve and track purchase orders through to receipt."),
                     ("Supplier Performance Review", "Measure supplier quality, delivery and cost performance over time."),
                 ]),
            dict(name="Warehousing & Distribution",
                 description="Store and move product, including temperature-controlled goods, without compromising it.",
                 owner="Distribution Operations Manager", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Goods Receipt & Putaway", "Receive, inspect and place incoming material into controlled storage."),
                     ("Order Picking & Packing", "Pick, pack and stage customer orders for despatch."),
                     ("Cold Chain Shipping", "Ship temperature-sensitive product with monitored, validated cold chain."),
                 ]),
            dict(name="Serialization & Traceability",
                 description="Know where every unit of product is, and be able to pull it back when needed.",
                 owner="Serialization Lead", importance="core", maturity=2, health="at-risk",
                 processes=[
                     ("Serial Number Management", "Generate, allocate and commission unit-level serial numbers."),
                     ("Track & Trace Reporting", "Report product movement events to regulators and trading partners."),
                     ("Recall Execution", "Identify, notify and retrieve affected product in a market action."),
                 ]),
        ]),
]

DOMAINS += [
    dict(
        name="Acquire & Serve Customers",
        description="Win veterinary practices, farms and distributors as customers, take their orders and keep them supported and billed.",
        owner="VP Commercial",
        importance="strategic", maturity=3, health="at-risk",
        capabilities=[
            dict(name="Marketing & Brand Management",
                 description="Create demand and protect the brand across species, segments and markets.",
                 owner="Head of Marketing", importance="strategic", maturity=3, health="ok",
                 processes=[
                     ("Campaign Planning", "Plan, budget and schedule multi-channel marketing campaigns."),
                     ("Digital Content Management", "Produce, approve and publish claims-compliant marketing content."),
                     ("Market Research", "Gather and analyse market, competitor and prescriber insight."),
                 ]),
            dict(name="Sales Pipeline Management",
                 description="Move opportunities from first contact to signed business, predictably.",
                 owner="Head of Sales Operations", importance="core", maturity=2, health="at-risk",
                 processes=[
                     ("Lead Qualification", "Assess inbound and sourced leads and decide which to pursue."),
                     ("Opportunity Management", "Progress qualified opportunities through the sales stages to close."),
                     ("Territory & Quota Planning", "Define sales territories and set quota for each field representative."),
                 ]),
            dict(name="Order Management",
                 description="Take a customer order and see it through to delivery, return or credit.",
                 owner="Customer Operations Manager", importance="core", maturity=3, health="watch",
                 processes=[
                     ("Order Capture", "Accept customer orders from field, portal, EDI and phone channels."),
                     ("Order Fulfilment Coordination", "Coordinate allocation, despatch and customer promise dates."),
                     ("Returns & Credits", "Process product returns and issue the resulting credits."),
                 ]),
            dict(name="Customer Support & Veterinary Services",
                 description="Answer the questions vets and farmers have about products, safely and on the record.",
                 owner="Head of Technical Services", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Case Intake & Triage", "Receive customer contacts and route them to the right responder."),
                     ("Technical Product Support", "Answer clinical and technical product questions from practitioners."),
                     ("Customer Feedback Management", "Capture and act on structured customer satisfaction feedback."),
                 ]),
            dict(name="Billing & Revenue",
                 description="Turn fulfilled orders into cash collected, without leakage or disputes.",
                 owner="Director, Revenue Operations", importance="core", maturity=2, health="at-risk",
                 processes=[
                     ("Invoice Generation", "Create and issue customer invoices from priced, fulfilled orders."),
                     ("Payment Processing", "Capture, apply and reconcile customer payments across channels."),
                     ("Collections", "Chase overdue balances and manage dunning through to resolution."),
                     ("Dispute Resolution", "Investigate and settle billing disputes and short payments."),
                 ]),
        ]),
    dict(
        name="Manage Finances",
        description="Plan, record, report and control the money so the business stays solvent, compliant and investable.",
        owner="Chief Financial Officer",
        importance="supporting", maturity=4, health="ok",
        capabilities=[
            dict(name="Financial Planning & Analysis",
                 description="Set the financial plan and explain the variance against it.",
                 owner="Head of FP&A", importance="supporting", maturity=4, health="ok",
                 processes=[
                     ("Budgeting", "Build and approve the annual operating and capital budget."),
                     ("Forecasting", "Refresh in-year financial forecasts as actuals and assumptions move."),
                     ("Management Reporting", "Publish periodic management accounts and performance packs."),
                 ]),
            dict(name="Accounting & Close",
                 description="Keep the books accurate and close them on time in every entity.",
                 owner="Group Financial Controller", importance="supporting", maturity=4, health="ok",
                 processes=[
                     ("General Ledger Accounting", "Post, review and control entries in the general ledger."),
                     ("Period-End Close", "Run the checklist that closes an accounting period across entities."),
                     ("Intercompany Reconciliation", "Match and settle balances between group companies."),
                 ]),
            dict(name="Treasury & Tax",
                 description="Manage cash, currency exposure and tax obligations across the markets served.",
                 owner="Group Treasurer", importance="supporting", maturity=3, health="ok",
                 processes=[
                     ("Cash Management", "Position and pool cash across bank accounts and entities."),
                     ("Tax Filing", "Prepare and file indirect and corporate tax returns per jurisdiction."),
                     ("FX Risk Management", "Hedge and monitor foreign exchange exposure."),
                 ]),
            dict(name="Procure-to-Pay Finance",
                 description="Pay suppliers accurately, on terms, with the right approvals behind every payment.",
                 owner="Head of Shared Services", importance="supporting", maturity=3, health="watch",
                 processes=[
                     ("Vendor Invoice Processing", "Capture, match and approve supplier invoices for payment."),
                     ("Payment Run Execution", "Execute and release scheduled outbound payment runs."),
                     ("Expense Management", "Process employee expense claims and corporate card spend."),
                 ]),
        ]),
    dict(
        name="Manage Human Capital",
        description="Attract, develop, pay and retain the people — including the GxP-trained staff the licences depend on.",
        owner="Chief People Officer",
        importance="supporting", maturity=3, health="ok",
        capabilities=[
            dict(name="Talent Acquisition",
                 description="Bring the right people in, quickly enough to matter.",
                 owner="Head of Talent", importance="supporting", maturity=3, health="ok",
                 processes=[
                     ("Workforce Requisition", "Raise and approve requisitions against approved headcount."),
                     ("Candidate Sourcing & Screening", "Source, screen and shortlist candidates for open roles."),
                     ("Onboarding", "Get a new joiner productive, equipped and compliantly trained."),
                 ]),
            dict(name="Learning & GxP Training",
                 description="Prove every employee is trained for the regulated work they actually do.",
                 owner="Training Compliance Manager", importance="core", maturity=3, health="watch",
                 processes=[
                     ("Training Needs Assessment", "Map roles to the curricula their regulated duties require."),
                     ("Curriculum Delivery", "Deliver and record completion of assigned training."),
                     ("Training Compliance Tracking", "Monitor overdue training and escalate compliance gaps."),
                 ]),
            dict(name="Compensation & Benefits",
                 description="Pay people correctly and competitively, everywhere they are employed.",
                 owner="Head of Reward", importance="supporting", maturity=4, health="ok",
                 processes=[
                     ("Payroll Processing", "Run and validate payroll cycles in each payroll country."),
                     ("Benefits Administration", "Administer enrolment and changes across benefit plans."),
                     ("Compensation Planning", "Run the annual salary and incentive review cycle."),
                 ]),
            dict(name="Employee Experience & Performance",
                 description="Keep people engaged, developing and clear on what good performance is.",
                 owner="Head of People Experience", importance="supporting", maturity=2, health="watch",
                 processes=[
                     ("Goal Setting & Reviews", "Set objectives and run performance review conversations."),
                     ("Employee Engagement Surveys", "Run engagement surveys and act on the results."),
                     ("Offboarding", "Exit leavers cleanly, including access and asset recovery."),
                 ]),
        ]),
    dict(
        name="Manage Risk, Safety & Compliance",
        description="See the risks to the company, its people and its animals before they become incidents — and prove control to regulators.",
        owner="Chief Risk & Compliance Officer",
        importance="core", maturity=3, health="watch",
        capabilities=[
            dict(name="Enterprise Risk Management",
                 description="Maintain one honest view of what could go seriously wrong and who is acting on it.",
                 owner="Head of Enterprise Risk", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Risk Identification & Assessment", "Identify, score and own risks across the enterprise register."),
                     ("Risk Mitigation Tracking", "Track mitigation actions to completion and re-score residual risk."),
                     ("Business Continuity Planning", "Maintain and exercise continuity plans for critical operations."),
                 ]),
            dict(name="Regulatory Compliance & Audit",
                 description="Stay inspection-ready and close findings before they escalate.",
                 owner="Head of Compliance", importance="core", maturity=4, health="ok",
                 processes=[
                     ("Internal Audit Execution", "Plan and execute internal audits against the audit schedule."),
                     ("Regulatory Inspection Readiness", "Prepare sites, people and records for authority inspections."),
                     ("Compliance Issue Remediation", "Remediate audit and inspection findings to verified closure."),
                 ]),
            dict(name="Environmental Health & Safety",
                 description="Protect employees, the public and the animals in the company's care.",
                 owner="EHS Director", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Incident Reporting", "Record workplace incidents and near misses and investigate causes."),
                     ("Hazard Assessment", "Assess and control chemical, biological and physical hazards."),
                     ("Animal Welfare Oversight", "Oversee welfare standards and ethical review for animal work."),
                 ]),
            dict(name="Sustainability & ESG Reporting",
                 description="Measure and disclose environmental and social performance to investors and regulators.",
                 owner="Head of Sustainability", importance="strategic", maturity=1, health="at-risk",
                 processes=[
                     ("Emissions Data Collection", "Collect scope 1, 2 and 3 emissions data from sites and suppliers."),
                     ("ESG Disclosure Preparation", "Assemble and assure the annual sustainability disclosure."),
                     ("Supplier Sustainability Screening", "Screen suppliers against environmental and social criteria."),
                 ]),
        ]),
    dict(
        name="Manage Information Technology",
        description="Run, secure, validate and evolve the technology every other domain on this map depends on.",
        owner="Chief Information Officer",
        importance="supporting", maturity=3, health="watch",
        capabilities=[
            dict(name="IT Service Management",
                 description="Keep services running and change them without breaking them.",
                 owner="Head of IT Service Management", importance="supporting", maturity=4, health="ok",
                 processes=[
                     ("Incident Management", "Detect, triage and restore service after IT incidents."),
                     ("Change Management", "Assess, approve and schedule changes to production services."),
                     ("Service Request Fulfilment", "Fulfil standard user requests through the service catalogue."),
                 ]),
            dict(name="Application Portfolio Management",
                 description="Know what applications exist, what they cost and which ones should die.",
                 owner="Head of Enterprise Architecture", importance="supporting", maturity=2, health="at-risk",
                 processes=[
                     ("Application Lifecycle Governance", "Govern applications from proposal through to decommissioning."),
                     ("Architecture Review", "Review proposed solutions against architecture standards."),
                     ("Technical Debt Remediation", "Prioritise and retire accumulated technical debt."),
                 ]),
            dict(name="Infrastructure & Cloud Operations",
                 description="Provide compute, storage and network that is available, recoverable and affordable.",
                 owner="Head of Infrastructure", importance="supporting", maturity=3, health="watch",
                 processes=[
                     ("Capacity Management", "Forecast and provision capacity ahead of demand."),
                     ("Backup & Recovery", "Protect data with tested backup and restore capability."),
                     ("Cloud Cost Management", "Monitor, allocate and reduce cloud consumption cost."),
                 ]),
            dict(name="Cybersecurity & Identity",
                 description="Keep attackers out and make sure the right people have exactly the right access.",
                 owner="Chief Information Security Officer", importance="core", maturity=3, health="watch",
                 processes=[
                     ("Identity & Access Management", "Provision, review and revoke identities and entitlements."),
                     ("Vulnerability Management", "Find, prioritise and remediate technical vulnerabilities."),
                     ("Security Monitoring", "Monitor, detect and respond to security events."),
                 ]),
            dict(name="Computer System Validation",
                 description="Prove regulated systems do what they are supposed to, and keep proving it.",
                 owner="CSV Lead", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Validation Planning", "Define validation scope, strategy and deliverables for a system."),
                     ("Qualification Testing", "Execute installation, operational and performance qualification."),
                     ("Periodic Review", "Periodically re-confirm a validated system remains in a validated state."),
                 ]),
        ]),
    dict(
        name="Manage Enterprise Data & Analytics",
        description="Make the organisation's data trustworthy, joined-up and usable for decisions and AI.",
        owner="Chief Data & Analytics Officer",
        importance="strategic", maturity=2, health="watch",
        capabilities=[
            dict(name="Data Governance",
                 description="Define who owns which data, what good looks like, and where it came from.",
                 owner="Head of Data Governance", importance="strategic", maturity=2, health="watch",
                 processes=[
                     ("Data Quality Management", "Profile, monitor and remediate data quality issues."),
                     ("Master Data Stewardship", "Steward golden records for product, customer and supplier."),
                     ("Metadata & Lineage Management", "Catalogue data assets and maintain end-to-end lineage."),
                 ]),
            dict(name="Data Engineering & Integration",
                 description="Move and shape data reliably between the systems that produce and consume it.",
                 owner="Head of Data Engineering", importance="core", maturity=3, health="ok",
                 processes=[
                     ("Pipeline Development", "Build and version data pipelines against agreed contracts."),
                     ("Data Ingestion Operations", "Run, monitor and recover scheduled and streaming ingestion."),
                     ("Data Model Management", "Design and evolve the shared analytical data models."),
                 ]),
            dict(name="Business Intelligence & Reporting",
                 description="Give every function numbers it can trust without asking IT first.",
                 owner="Head of Business Intelligence", importance="supporting", maturity=3, health="ok",
                 processes=[
                     ("Report Development", "Build and certify reports and dashboards for business consumers."),
                     ("Self-Service Analytics Enablement", "Equip business analysts to answer their own questions safely."),
                     ("KPI Definition & Publication", "Define, calculate and publish agreed enterprise KPIs."),
                 ]),
            dict(name="AI/ML Enablement",
                 description="Take AI ideas from intake to production models that are monitored and governed.",
                 owner="Head of AI Center of Excellence", importance="strategic", maturity=2, health="watch",
                 processes=[
                     ("Use Case Intake & Triage", "Capture, score and triage candidate AI use cases."),
                     ("Model Development", "Develop, evaluate and document candidate models."),
                     ("Model Monitoring & Governance", "Monitor deployed models for drift, bias and control compliance."),
                 ]),
        ]),
]

# Level B4 activities, attached to a handful of processes that benefit from one more zoom level.
ACTIVITIES = {
    "Invoice Generation": [
        ("Price & Tax Determination", "Apply contract pricing, discounts and tax rules to fulfilled order lines."),
        ("Invoice Document Creation", "Render the legal invoice document in the customer's required format."),
        ("Invoice Delivery", "Transmit the invoice by EDI, portal, email or post per customer preference."),
        ("Invoice Posting to Ledger", "Post the receivable and revenue entries to the general ledger."),
    ],
    "Payment Processing": [
        ("Payment Authorisation", "Authorise card and direct debit payments with the acquiring bank."),
        ("Cash Application", "Match incoming receipts to open receivables."),
        ("Payment Exception Handling", "Work failed, partial and unidentified payments to resolution."),
    ],
    "Batch Execution & Recording": [
        ("Recipe Download to Line", "Push the approved master recipe to the line control system."),
        ("In-Process Check Recording", "Record in-process checks and weights against the batch record."),
        ("Electronic Signature Capture", "Capture Part 11 compliant signatures at each controlled step."),
        ("Batch Record Review by Exception", "Review only the flagged exceptions rather than the whole record."),
    ],
    "Analytical Testing": [
        ("Method Selection", "Select the validated analytical method for the sample and specification."),
        ("Instrument Run Execution", "Execute the run on a qualified instrument and capture raw data."),
        ("Result Review & Approval", "Second-person review and approval of calculated results."),
    ],
    "Adverse Event Intake": [
        ("Contact Capture", "Capture the reporter, animal and product details of a suspected event."),
        ("Duplicate Detection", "Check the incoming report against existing cases."),
        ("Initial Seriousness Triage", "Classify the case seriousness to set the reporting clock."),
    ],
    "Order Capture": [
        ("Customer & Product Validation", "Validate the customer account, licence and product eligibility."),
        ("Credit Check", "Check available credit and blocked-account status before acceptance."),
        ("Order Confirmation", "Confirm accepted lines, price and promised date back to the customer."),
    ],
    "Cold Chain Shipping": [
        ("Packout Configuration", "Select the validated packout for lane, season and duration."),
        ("Temperature Monitoring", "Attach and read loggers that evidence the chain was maintained."),
        ("Excursion Review", "Assess temperature excursions and decide product disposition."),
    ],
    "Identity & Access Management": [
        ("Joiner Provisioning", "Provision accounts and entitlements for a new joiner."),
        ("Access Recertification", "Periodically re-attest that entitlements are still justified."),
        ("Leaver Deprovisioning", "Revoke access promptly when someone leaves or changes role."),
    ],
}
