"""Application portfolio for the demo model.

Each entry: (slug, name, description, category, vendor, lifecycle, criticality,
             cost_band, archetype, [supported process/capability names])
A support target is a process name by default; prefix with "cap:" to attach the
application at capability level (B2) instead.

archetype drives how the IT lens (T2-T5) is generated for the application:
  three_tier | event_driven | data_platform | legacy_monolith | mobile | saas
"""

APPS = [
    # --- Discover & Develop Products -------------------------------------
    ("helix-eln", "Helix ELN", "Electronic lab notebook where discovery and preclinical scientists design, run and witness experiments.",
     "Lab Informatics", "Benchmark Labs", "active", "high", "M", "three_tier",
     ["Target Identification", "Compound Screening", "Lead Optimization", "In Vitro Study Execution"]),
    ("assayiq", "AssayIQ Screening Platform", "High-throughput screening execution and assay result capture for the discovery labs.",
     "Lab Informatics", "Internal", "active", "medium", "S", "event_driven",
     ["Compound Screening"]),
    ("preclinix", "PreCliniX Study Manager", "Preclinical study design, scheduling, welfare records and endpoint capture.",
     "Lab Informatics", "Preclinical Systems Ltd", "active", "high", "M", "three_tier",
     ["Animal Model Study Execution", "Toxicology Assessment", "Animal Welfare Oversight"]),
    ("formuladesk", "FormulaDesk", "Formulation design of record: recipes, excipient libraries and development trial history.",
     "R&D", "Internal", "active", "medium", "S", "three_tier",
     ["Formulation Design", "Delivery Device Engineering"]),
    ("stabitrack", "StabiTrack", "Stability protocol scheduling, timepoint pull tracking and shelf-life determination.",
     "Lab Informatics", "Internal", "active", "high", "S", "three_tier",
     ["Stability Study Management"]),
    ("portfoliopro", "PortfolioPro", "Research portfolio scoring, stage-gating and programme budget tracking.",
     "Portfolio", "Northgate Software", "active", "medium", "M", "saas",
     ["Portfolio Prioritization", "Research Project Intake", "Discovery Budget Tracking"]),

    # --- Clinical & Regulatory -------------------------------------------
    ("vettrial-ctms", "VetTrial CTMS", "Clinical trial operations: protocols, site activation, monitoring visits and study milestones.",
     "Clinical", "TrialWorks", "active", "high", "L", "three_tier",
     ["Study Design & Protocol Authoring", "Site Selection & Activation"]),
    ("clincap-edc", "ClinCap EDC", "Validated electronic data capture used by investigator sites to record study observations.",
     "Clinical", "ClinCap", "active", "critical", "M", "saas",
     ["Clinical Data Capture"]),
    ("regdossier", "RegDossier RIM", "Regulatory information management: product registrations, dossier assembly and commitments.",
     "Regulatory", "RegSys International", "active", "critical", "L", "three_tier",
     ["Dossier Assembly", "Submission Tracking"]),
    ("esubmit-gateway", "eSubmit Gateway", "Electronic submission gateway to veterinary health authorities.",
     "Regulatory", "RegSys International", "active", "critical", "S", "three_tier",
     ["Health Authority Submission"]),
    ("labelworks", "LabelWorks", "Structured label content authoring, versioning and packaging artwork approval workflow.",
     "Regulatory", "Internal", "active", "high", "M", "three_tier",
     ["Label Content Management", "Artwork Approval"]),
    ("regintel-feed", "RegIntel Feed", "Subscription intelligence service that streams veterinary regulatory changes by market.",
     "Regulatory", "GlobalReg Intelligence", "active", "medium", "S", "saas",
     ["Regulatory Change Monitoring"]),
    ("safetyvault", "SafetyVault PV", "Pharmacovigilance case management, causality assessment and periodic safety reporting.",
     "Safety", "SafetyVault", "active", "critical", "L", "three_tier",
     ["Adverse Event Intake", "Case Processing & Assessment", "Periodic Safety Reporting"]),

    # --- Manufacture & Quality -------------------------------------------
    ("auriga-erp", "Auriga ERP", "The company's core ERP: materials, production orders, procurement, inventory, finance and order-to-cash.",
     "ERP", "Auriga Systems", "active", "critical", "XL", "legacy_monolith",
     ["Master Production Scheduling", "Goods Receipt & Putaway", "Purchase Order Management",
      "General Ledger Accounting", "Period-End Close", "Vendor Invoice Processing",
      "Payment Run Execution", "Order Capture", "Order Fulfilment Coordination", "Returns & Credits",
      "Intercompany Reconciliation"]),
    ("prodline-mes", "ProdLine MES", "Manufacturing execution: recipe download, electronic batch records and line performance.",
     "Manufacturing", "ProdLine", "active", "critical", "L", "three_tier",
     ["Batch Execution & Recording", "Line Changeover Management"]),
    ("labcore-lims", "LabCore LIMS", "Laboratory information management for QC sample lifecycle, testing and specifications.",
     "Lab Informatics", "LabCore", "active", "critical", "L", "three_tier",
     ["Sample Management", "Analytical Testing", "Out-of-Specification Investigation"]),
    ("qualisphere-qms", "QualiSphere QMS", "Quality management system for deviations, CAPA, change control and audit findings.",
     "Quality", "QualiSphere", "active", "critical", "L", "three_tier",
     ["Deviation Management", "CAPA Management", "Compliance Issue Remediation", "Internal Audit Execution"]),
    ("releasedesk", "ReleaseDesk", "Review-by-exception batch review and QP disposition of finished batches.",
     "Quality", "Internal", "active", "critical", "S", "three_tier",
     ["Batch Release & Disposition"]),
    ("maintainx-cmms", "MaintainX CMMS", "Computerised maintenance management for plant assets, work orders and calibration.",
     "Engineering", "MaintainX", "active", "high", "M", "three_tier",
     ["Preventive Maintenance", "Calibration Management"]),
    ("valdocs", "ValDocs", "Validation document management: protocols, executed qualification records and periodic reviews.",
     "Quality", "Internal", "active", "high", "M", "three_tier",
     ["Cleaning Validation", "Validation Documentation", "Validation Planning", "Qualification Testing", "Periodic Review"]),
    ("transferhub", "TransferHub", "Technology transfer workspace for process characterisation and site transfer packages.",
     "Manufacturing", "Internal", "plan", "medium", "S", "three_tier",
     ["Process Characterization", "Site Transfer Execution"]),
    ("edms-docuvault", "DocuVault EDMS", "Controlled document repository for SOPs, protocols and reports across GxP functions.",
     "Content", "DocuVault", "active", "critical", "L", "three_tier",
     ["cap:Quality Assurance & Compliance", "cap:Regulatory Submission Management", "Curriculum Delivery"]),

    # --- Supply Chain -----------------------------------------------------
    ("planwise-aps", "PlanWise APS", "Advanced planning: statistical forecasting, supply network planning and inventory targets.",
     "Supply Chain", "PlanWise", "active", "high", "L", "three_tier",
     ["Demand Forecasting", "Supply Network Planning", "Inventory Optimization"]),
    ("supplierhub", "SupplierHub SRM", "Supplier qualification records, audits, scorecards and performance reviews.",
     "Supply Chain", "SupplierHub", "active", "medium", "M", "saas",
     ["Supplier Qualification", "Supplier Performance Review"]),
    ("storeflow-wms", "StoreFlow WMS", "Warehouse management for receipt, putaway, picking, packing and despatch.",
     "Supply Chain", "StoreFlow", "active", "critical", "L", "three_tier",
     ["Goods Receipt & Putaway", "Order Picking & Packing"]),
    ("coldlink-tms", "ColdLink TMS", "Transport management with validated cold-chain lanes and carrier integration.",
     "Supply Chain", "ColdLink", "active", "high", "M", "three_tier",
     ["Cold Chain Shipping"]),
    ("serialtrack", "SerialTrack", "Serialisation repository: serial number allocation, commissioning and track-and-trace reporting.",
     "Supply Chain", "Internal", "active", "high", "M", "event_driven",
     ["Serial Number Management", "Track & Trace Reporting", "Recall Execution"]),
    ("coldchain-hub", "ColdChain Sensor Hub", "Ingests telemetry from shipment temperature loggers and raises excursion alerts.",
     "IoT", "Internal", "active", "high", "S", "event_driven",
     ["Cold Chain Shipping"]),

    # --- Commercial -------------------------------------------------------
    ("vetconnect-crm", "VetConnect CRM", "Primary CRM for field sales: accounts, opportunities, call plans and territory management.",
     "CRM", "VetConnect", "active", "critical", "L", "saas",
     ["Lead Qualification", "Opportunity Management", "Territory & Quota Planning", "Case Intake & Triage"]),
    ("clarion-crm", "Clarion CRM (Legacy)", "Legacy regional CRM still used by the EU field team; overlaps VetConnect and is scheduled to retire.",
     "CRM", "Clarion", "phase-out", "medium", "M", "legacy_monolith",
     ["Lead Qualification", "Opportunity Management", "Territory & Quota Planning"]),
    ("marketmix", "MarketMix Campaign Manager", "Campaign planning, budgeting, execution and multi-channel performance tracking.",
     "Marketing", "MarketMix", "active", "medium", "M", "saas",
     ["Campaign Planning"]),
    ("contenthub-dam", "ContentHub DAM", "Digital asset management and claims-approval workflow for marketing content.",
     "Content", "ContentHub", "active", "medium", "S", "three_tier",
     ["Digital Content Management"]),
    ("insightpanel", "InsightPanel Market Research", "Panel-based market and prescriber research with syndicated data subscriptions.",
     "Marketing", "InsightPanel", "active", "low", "S", "saas",
     ["Market Research"]),
    ("ordercentral", "OrderCentral", "Order orchestration hub across field, portal, EDI and telephone order channels.",
     "Commercial", "Internal", "active", "critical", "L", "event_driven",
     ["Order Capture", "Order Fulfilment Coordination", "Returns & Credits"]),
    ("vetstore", "VetStore eCommerce", "Self-service ordering portal and mobile app for veterinary practices and distributors.",
     "Commercial", "Internal", "active", "high", "M", "mobile",
     ["Order Capture", "Technical Product Support"]),
    ("vetsupport-desk", "VetSupport Service Desk", "Customer service desk for veterinary technical enquiries and complaint intake.",
     "Service", "ServiceOne", "active", "high", "M", "saas",
     ["Case Intake & Triage", "Technical Product Support"]),
    ("feedbackloop", "FeedbackLoop", "Survey platform used for both customer satisfaction and employee engagement studies.",
     "Survey", "FeedbackLoop", "active", "low", "S", "saas",
     ["Customer Feedback Management", "Employee Engagement Surveys"]),
    ("billwise", "BillWise Billing", "Invoice generation, billing schedules, credit notes and dispute case handling.",
     "Finance", "BillWise", "active", "critical", "L", "three_tier",
     ["Invoice Generation", "Dispute Resolution"]),
    ("paygate", "PayGate Payment Hub", "Payment orchestration across card, direct debit and bank transfer rails with cash application.",
     "Finance", "Internal", "active", "critical", "M", "event_driven",
     ["Payment Processing"]),
    ("collectiq", "CollectIQ", "Collections workflow, dunning campaigns and promise-to-pay tracking.",
     "Finance", "CollectIQ", "active", "medium", "S", "saas",
     ["Collections"]),

    # --- Finance ----------------------------------------------------------
    ("planalytics", "Planalytics FP&A", "Driver-based planning, forecasting and management reporting for the finance function.",
     "Finance", "Planalytics", "active", "high", "L", "saas",
     ["Budgeting", "Forecasting", "Management Reporting"]),
    ("closemaster", "CloseMaster", "Financial close orchestration: task checklists, reconciliations and close certification.",
     "Finance", "CloseMaster", "active", "high", "M", "saas",
     ["Period-End Close", "Intercompany Reconciliation"]),
    ("treasuryone", "TreasuryOne", "Cash positioning, bank connectivity, FX exposure capture and hedge accounting.",
     "Finance", "TreasuryOne", "active", "high", "M", "saas",
     ["Cash Management", "FX Risk Management"]),
    ("taxbridge", "TaxBridge", "Indirect tax determination and statutory filing service across jurisdictions.",
     "Finance", "TaxBridge", "active", "medium", "S", "saas",
     ["Tax Filing"]),
    ("invoiceiq", "InvoiceIQ AP Automation", "Supplier invoice capture, OCR extraction, three-way match and approval routing.",
     "Finance", "InvoiceIQ", "active", "high", "M", "three_tier",
     ["Vendor Invoice Processing", "Payment Run Execution"]),
    ("expenseflow", "ExpenseFlow", "Employee expense claims, corporate card feeds and travel policy enforcement.",
     "Finance", "ExpenseFlow", "active", "low", "S", "saas",
     ["Expense Management"]),

    # --- Human Capital ----------------------------------------------------
    ("peoplecore-hcm", "PeopleCore HCM", "Core HR system of record: worker data, org structure, performance and compensation cycles.",
     "HR", "PeopleCore", "active", "high", "L", "saas",
     ["Workforce Requisition", "Onboarding", "Goal Setting & Reviews", "Compensation Planning", "Offboarding"]),
    ("recruitly-ats", "Recruitly ATS", "Applicant tracking: sourcing, screening, interview scheduling and offers.",
     "HR", "Recruitly", "active", "medium", "S", "saas",
     ["Candidate Sourcing & Screening"]),
    ("learnpath-lms", "LearnPath LMS", "Learning management with GxP curricula, e-signature on training and compliance dashboards.",
     "HR", "LearnPath", "active", "critical", "M", "three_tier",
     ["Training Needs Assessment", "Curriculum Delivery", "Training Compliance Tracking"]),
    ("payrollpro", "PayrollPro", "Multi-country payroll processing and benefits administration.",
     "HR", "PayrollPro", "active", "critical", "M", "saas",
     ["Payroll Processing", "Benefits Administration"]),

    # --- Risk, Safety & Compliance ---------------------------------------
    ("riskregistry", "RiskRegistry GRC", "Enterprise risk register, control library, audit planning and inspection readiness workspace.",
     "GRC", "RiskRegistry", "active", "high", "M", "three_tier",
     ["Risk Identification & Assessment", "Risk Mitigation Tracking", "Regulatory Inspection Readiness"]),
    ("continuityplanner", "ContinuityPlanner", "Business continuity and disaster recovery plan authoring and exercise tracking.",
     "GRC", "ContinuityPlanner", "plan", "medium", "S", "saas",
     ["Business Continuity Planning"]),
    ("safeguard-ehs", "SafeGuard EHS", "Environmental, health and safety incident reporting, hazard assessment and welfare oversight.",
     "EHS", "SafeGuard", "active", "high", "M", "three_tier",
     ["Incident Reporting", "Hazard Assessment", "Animal Welfare Oversight"]),

    # --- Information Technology -------------------------------------------
    ("serviceone-itsm", "ServiceOne ITSM", "IT service management: incidents, changes, problems and the service request catalogue.",
     "ITSM", "ServiceOne", "active", "critical", "L", "saas",
     ["Incident Management", "Change Management", "Service Request Fulfilment"]),
    ("assetcore-cmdb", "AssetCore CMDB", "Configuration management database holding configuration items and their dependencies.",
     "ITSM", "ServiceOne", "active", "high", "M", "three_tier",
     ["Application Lifecycle Governance", "Technical Debt Remediation", "Capacity Management"]),
    ("archimap", "ArchiMap EA Repository", "Enterprise architecture repository holding capability maps, application landscape and standards.",
     "Architecture", "ArchiMap", "active", "medium", "S", "three_tier",
     ["Architecture Review", "Application Lifecycle Governance"]),
    ("identityone", "IdentityOne IAM", "Enterprise identity provider, single sign-on, entitlement lifecycle and access recertification.",
     "Security", "IdentityOne", "active", "critical", "L", "three_tier",
     ["Identity & Access Management"]),
    ("vulnwatch", "VulnWatch", "Vulnerability scanning, prioritisation and remediation tracking across the estate.",
     "Security", "VulnWatch", "active", "high", "M", "three_tier",
     ["Vulnerability Management"]),
    ("sentinelops-siem", "SentinelOps SIEM", "Security information and event management with detection engineering and response playbooks.",
     "Security", "SentinelOps", "active", "critical", "L", "data_platform",
     ["Security Monitoring"]),
    ("backupvault", "BackupVault", "Enterprise backup, immutable retention and restore testing service.",
     "Infrastructure", "BackupVault", "active", "critical", "M", "three_tier",
     ["Backup & Recovery"]),
    ("optiq-cloudcost", "OptiQ Cloud Cost", "Cloud consumption analytics, showback and rightsizing recommendations.",
     "Infrastructure", "OptiQ", "active", "low", "S", "saas",
     ["Cloud Cost Management"]),

    # --- Data & Analytics --------------------------------------------------
    ("insightlake", "InsightLake Data Platform", "Lakehouse platform holding curated enterprise data products and the pipelines that build them.",
     "Data", "Internal", "active", "critical", "XL", "data_platform",
     ["Pipeline Development", "Data Ingestion Operations", "Data Model Management", "Self-Service Analytics Enablement"]),
    ("vistareports-bi", "VistaReports BI", "Enterprise BI and dashboard layer over curated data products.",
     "Analytics", "VistaReports", "active", "high", "L", "three_tier",
     ["Report Development", "KPI Definition & Publication", "Management Reporting"]),
    ("datasteward-mdm", "DataSteward MDM", "Master data management for product, customer, supplier and site golden records.",
     "Data", "DataSteward", "active", "critical", "L", "three_tier",
     ["Master Data Stewardship", "Data Quality Management"]),
    ("lineageiq", "LineageIQ Catalog", "Data catalogue with automated lineage harvesting and glossary management.",
     "Data", "LineageIQ", "active", "medium", "M", "data_platform",
     ["Metadata & Lineage Management"]),
    ("modelforge", "ModelForge MLOps", "Model registry, training pipelines, deployment and drift monitoring for production models.",
     "AI/ML", "Internal", "active", "high", "M", "data_platform",
     ["Model Development", "Model Monitoring & Governance"]),
    ("usecasehub", "UseCaseHub", "Intake, scoring and stage-gating of candidate AI use cases for the AI Center of Excellence.",
     "AI/ML", "Internal", "active", "low", "S", "three_tier",
     ["Use Case Intake & Triage"]),
]
